config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'links#index'

  resources :links, only: [:new, :create, :show] do
    member do
      post 'upvote'
    end
  end
  mount API::Base => '/'
end

app/models/link.rb
class Link < ActiveRecord::Base
  IMAGE_FORMATS = %w(.jpg .png .gif)

  validates :title, presence: true
  validates :url, presence: true
  validates :url, uniqueness: true

  def upvote
    increment!(:upvotes)
  end

  def score
    upvotes - downvotes
  end

  def self.hottest_first
    order('upvotes - downvotes DESC')
  end

  def image?
    url.end_with? *IMAGE_FORMATS
  end
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  as_enum :role, [:member, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to @link
    else
      render :new
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote

    redirect_to :back
  end

  private

  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/prototype_controller.rb
class PrototypeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def image_placeholder(args)
    width = args[:width] || '300'
    height = args[:height] || '300'
    text = args[:text] || "#{width} x #{height}"
    classes = args[:class] || ""

    image_tag "http://placehold.it/#{width}x#{height}&text=#{text}", :class => "#{classes}"
  end
end

app/helpers/links_helper.rb
module LinksHelper
  def formatted_score_for(link)
    "#{link.score} (+#{link.upvotes}, -#{link.downvotes})"
  end
end

app/views/common/_error_messages.html.erb
<% if target.errors.any? %>
  <div>
    <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
      <ul>
        <% target.errors.messages.each do |message| %>
          <li><%= message[1].last %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/common/_footer.html.erb
<!-- footer -->
<footer>

</footer>

app/views/common/_header.html.erb
<!-- header -->
<header>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TITLE</title>
    <meta name="description" content="DESCRIPTION">
    <meta name="viewport" content="width=device-width">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <%= growlyflash_static_notices %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'modernizr' %>

  </head>
  <body class='<%= "#{controller.controller_name}-#{controller.action_name}" %>'>
      <!--[if lt IE 7]>
          <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
      <![endif]-->

  <%= render :partial => 'common/header' %>

  <%= yield %>

  <%= render :partial => 'common/footer' %>



  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, 'data-turbolinks-eval' => false %>
  <%= yield :handwrite_js %>

  </body>
</html>

app/views/links/_link.html.erb
<%= link_to link.url do %>
  <%= link.title %>
  <%= image_tag link.url if link.image? %>
<% end %>

app/views/links/index.html.erb
<%= link_to "Submit a new link", new_link_path %>

<div>
  <% @links.each do |link| %>
    <div id="link_<%= link.id %>">
      <%= link_to link.title, link.url, target: '_blank' %> | <%= link_to '參與討論', link_path(link) %> | <%= link_to "讚", upvote_link_path(link), method: :post %> <span data-role="score"><%= link.score %></span>
    </div>
  <% end %>
</div>

app/views/links/new.html.erb
<%= form_for(@link) do |f| %>
  <%= render partial: "common/error_messages", locals: {target: @link} %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <%= f.submit 'Submit!' %>
<% end %>

app/views/links/show.html.erb
<h1><%= render partial: 'link', locals: {link: @link} %></h1>

<div>
  <h3>Title</h3>
  <%= @link.title %>
</div>

<div>
  <h3>Url</h3>
  <%= @link.url %>
</div>

app/views/prototype/index.html.erb
FrontEnd UI preview